### ISSUE TITLE
Suggestion: Screenshot

### ISSUE THREAD

**Issue by MasterIceZ** [itzmeowww/jajeebkorreebjeeb#11]
### Suggestion
To push new screenshot from `github action`, `screenshots-workflow.yml` should have `commit` and `push` command.

Example of the steps is [here](https://github.com/marketplace/actions/github-push).

Best Regards,
[MasterIceZ](https://github.com/mastericez)
<img src="https://user-images.githubusercontent.com/64594596/137335956-0643ec5c-8b0e-453c-a2fe-ef130f826fc9.png"/>

**Comment by itzmeowww** [comment]
Thank for the suggestion! I hope my code will work properly now.
